/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ambimmort.uc.zfserver.ui;

/**
 *
 * @author 定巍
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPIEndPointPanel3 = new com.ambimmort.uc.zfserver.ui.DPIEndPointPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        dPIEndPointPanel5 = new com.ambimmort.uc.zfserver.ui.DPIEndPointPanel();
        dPIEndPointPanel7 = new com.ambimmort.uc.zfserver.ui.DPIEndPointPanel();
        dPIEndPointPanel6 = new com.ambimmort.uc.zfserver.ui.DPIEndPointPanel();
        dPIEndPointPanel8 = new com.ambimmort.uc.zfserver.ui.DPIEndPointPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 300));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(600, 32767));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jPanel2.add(dPIEndPointPanel5);
        jPanel2.add(dPIEndPointPanel7);
        jPanel2.add(dPIEndPointPanel6);
        jPanel2.add(dPIEndPointPanel8);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ambimmort.uc.zfserver.ui.DPIEndPointPanel dPIEndPointPanel3;
    private com.ambimmort.uc.zfserver.ui.DPIEndPointPanel dPIEndPointPanel5;
    private com.ambimmort.uc.zfserver.ui.DPIEndPointPanel dPIEndPointPanel6;
    private com.ambimmort.uc.zfserver.ui.DPIEndPointPanel dPIEndPointPanel7;
    private com.ambimmort.uc.zfserver.ui.DPIEndPointPanel dPIEndPointPanel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
